using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Xunit;

namespace Reliever.BudgetEnvelope.Stub.Tests;

/// <summary>
/// CI unit tests — verify, independently of bus availability, that:
///   1. Every payload generated by <see cref="PayloadFactory"/> validates
///      against the runtime JSON Schema RVT.BSP.004.CONSUMPTION_RECORDED.
///   2. The cadence guard enforces the [1, 10] events/min default range,
///      with an explicit override flag for outside-range values.
///   3. consumed_amount progresses monotonically toward cap_amount across
///      successive publications for the same envelope (domain-event-DDD
///      transition data — not random snapshots).
///   4. Payloads honor the schema's invariants on bounds (cap_amount > 0,
///      consumed_amount >= 0).
///
/// These checks satisfy the Definition of Done requirement that "every
/// payload published by the stub validates against the runtime JSON Schema
/// (automated check)".
/// </summary>
public class PayloadValidationTests
{
    private const string SchemaRelativePath =
        "schemas/RVT.BSP.004.CONSUMPTION_RECORDED.schema.json";

    private static SchemaValidator LoadValidator()
    {
        var path = Path.Combine(AppContext.BaseDirectory, SchemaRelativePath);
        return SchemaValidator.FromFile(path);
    }

    private static StubOptions DefaultOptions() => new()
    {
        Active = true,
        CadencePerMinute = 5,
        ExchangeName = "bsp.004.env-events",
        RoutingKey = "EVT.BSP.004.ENVELOPE_CONSUMED.RVT.BSP.004.CONSUMPTION_RECORDED",
        SimulatedCases = new List<SimulatedCase>
        {
            new()
            {
                CaseId = "CASE-RELIEVER-2026-000001",
                TierLabel = "T1",
                PeriodStart = "2026-05-01",
                PeriodEnd   = "2026-05-31",
                Envelopes = new List<SimulatedEnvelope>
                {
                    new() { Category = "ALIMENTATION", CapAmount = 250.00m },
                    new() { Category = "TRANSPORT",    CapAmount =  80.00m },
                }
            },
            new()
            {
                CaseId = "CASE-RELIEVER-2026-000002",
                TierLabel = "T2",
                PeriodStart = "2026-05-01",
                PeriodEnd   = "2026-05-31",
                Envelopes = new List<SimulatedEnvelope>
                {
                    new() { Category = "ALIMENTATION", CapAmount = 350.00m },
                    new() { Category = "LOGEMENT",     CapAmount = 500.00m },
                }
            }
        },
    };

    [Fact]
    public void Generated_payloads_validate_against_runtime_schema()
    {
        var validator = LoadValidator();
        var factory = new PayloadFactory(DefaultOptions(), new Random(42));

        for (var i = 0; i < 200; i++)
        {
            var payload = factory.BuildOne();
            var errors = validator.Validate(payload);
            Assert.True(errors.Count == 0,
                $"Payload #{i} failed validation: {string.Join("; ", errors)}\nPayload: {payload}");
        }
    }

    [Fact]
    public void EnsureValid_throws_on_corrupted_payload()
    {
        var validator = LoadValidator();
        var factory = new PayloadFactory(DefaultOptions(), new Random(7));
        var payload = factory.BuildOne();

        // Remove a required field to force a schema violation.
        payload.Remove("case_id");

        Assert.Throws<InvalidPayloadException>(() => validator.EnsureValid(payload));
    }

    [Fact]
    public void Consumed_amount_progresses_toward_cap_then_resets()
    {
        // Single case, single envelope: deterministic enough to observe the
        // monotonic progression and the post-cap reset.
        var opts = new StubOptions
        {
            Active = true,
            CadencePerMinute = 5,
            ExchangeName = "bsp.004.env-events",
            RoutingKey = "EVT.BSP.004.ENVELOPE_CONSUMED.RVT.BSP.004.CONSUMPTION_RECORDED",
            SimulatedCases = new List<SimulatedCase>
            {
                new()
                {
                    CaseId = "CASE-PROGRESSION-TEST",
                    TierLabel = "T1",
                    PeriodStart = "2026-05-01",
                    PeriodEnd   = "2026-05-31",
                    Envelopes = new List<SimulatedEnvelope>
                    {
                        new() { Category = "ALIMENTATION", CapAmount = 100.00m }
                    }
                }
            },
        };

        var factory = new PayloadFactory(opts, new Random(13));
        var values = new List<double>();
        var caps = new List<double>();

        for (var i = 0; i < 50; i++)
        {
            var payload = factory.BuildOne();
            values.Add(payload["consumed_amount"]!.GetValue<double>());
            caps.Add(payload["cap_amount"]!.GetValue<double>());
        }

        // cap_amount stays constant per envelope.
        Assert.All(caps, c => Assert.Equal(100.0, c));

        // consumed_amount stays within bounds [0, cap_amount].
        Assert.All(values, v => Assert.InRange(v, 0.0, 100.0));

        // We must observe at least one full cycle: a value reaching the cap,
        // followed later by a smaller value (post-reset).
        var hitCap = values.Any(v => v >= 100.0);
        Assert.True(hitCap, "Expected at least one publication to reach cap_amount over 50 iterations.");
    }

    [Fact]
    public void Payload_carries_all_required_fields_with_correct_types()
    {
        var validator = LoadValidator();
        var factory = new PayloadFactory(DefaultOptions(), new Random(99));
        var payload = factory.BuildOne();

        Assert.NotNull(payload["allocation_id"]);
        Assert.NotNull(payload["case_id"]);
        Assert.NotNull(payload["category"]);
        Assert.NotNull(payload["cap_amount"]);
        Assert.NotNull(payload["consumed_amount"]);
        Assert.NotNull(payload["period_start"]);
        Assert.NotNull(payload["period_end"]);

        // Schema invariants: cap_amount > 0, consumed_amount >= 0.
        Assert.True(payload["cap_amount"]!.GetValue<double>() > 0);
        Assert.True(payload["consumed_amount"]!.GetValue<double>() >= 0);

        Assert.Empty(validator.Validate(payload));
    }

    [Theory]
    [InlineData(1)]
    [InlineData(5)]
    [InlineData(10)]
    public void Cadence_within_default_range_is_accepted(int rate)
    {
        var opts = DefaultOptions();
        opts.CadencePerMinute = rate;
        opts.CadenceOutsideRangeOverride = false;

        var ex = Record.Exception(() => Worker.ValidateCadence(opts));
        Assert.Null(ex);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(11)]
    [InlineData(60)]
    public void Cadence_outside_default_range_requires_override(int rate)
    {
        var opts = DefaultOptions();
        opts.CadencePerMinute = rate;
        opts.CadenceOutsideRangeOverride = false;

        Assert.Throws<InvalidOperationException>(() => Worker.ValidateCadence(opts));
    }

    [Theory]
    [InlineData(11)]
    [InlineData(60)]
    public void Cadence_outside_default_range_with_override_is_accepted(int rate)
    {
        var opts = DefaultOptions();
        opts.CadencePerMinute = rate;
        opts.CadenceOutsideRangeOverride = true;

        var ex = Record.Exception(() => Worker.ValidateCadence(opts));
        Assert.Null(ex);
    }
}
