using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using NJsonSchema;
using Reliever.TierManagement.Stub;
using Xunit;

namespace Reliever.TierManagement.Stub.Tests;

/// <summary>
/// CI unit tests verifying that the development stub honors the Definition of Done:
///
///  - every payload generated by PayloadFactory validates against the runtime
///    JSON Schema (RVT.BSP.001.FRANCHISSEMENT_ENREGISTRE);
///  - the upward-direction constraint (sens=FRANCHISSEMENT) is always satisfied;
///  - the schema's $id encodes the version segment and the x-bcm-version annotation
///    matches.
///
/// These tests are the automated guardrail recommended by the DoD; they fail
/// loudly the moment the stub or the schema drifts from the BCM contract.
/// </summary>
public sealed class PayloadValidatesAgainstSchemaTests
{
    private const string SchemaRelativePath = "schemas/RVT.BSP.001.FRANCHISSEMENT_ENREGISTRE.schema.json";

    private static StubOptions DefaultOptions() => new()
    {
        Active = true,
        EventsPerMinute = 6,
        AllowOutOfRangeCadence = false,
        CaseIds = new() { "DOS-TEST-1", "DOS-TEST-2", "DOS-TEST-3" },
        TierProgression = new() { "T0", "T1", "T2", "T3" },
        Schema = new SchemaOptions { RuntimeSchemaPath = SchemaRelativePath }
    };

    private static SchemaValidator BuildValidator(StubOptions options)
        => new(Options.Create(options), NullLogger<SchemaValidator>.Instance);

    private static PayloadFactory BuildFactory(StubOptions options)
        => new(Options.Create(options), NullLogger<PayloadFactory>.Instance);

    [Fact]
    public void Schema_File_Is_Present_Next_To_Tests()
    {
        var path = Path.Combine(AppContext.BaseDirectory, SchemaRelativePath);
        Assert.True(File.Exists(path),
            $"Runtime schema must be copied to test output at '{path}'.");
    }

    [Fact]
    public void Schema_Encodes_Version_In_Both_Id_And_X_Bcm_Version()
    {
        // Parse the raw JSON: NJsonSchema's loader normalises some root-level
        // properties — assert at the source-of-truth level (the JSON document).
        var path = Path.Combine(AppContext.BaseDirectory, SchemaRelativePath);
        var schemaJson = File.ReadAllText(path);
        using var doc = System.Text.Json.JsonDocument.Parse(schemaJson);
        var root = doc.RootElement;

        Assert.True(root.TryGetProperty("$id", out var id), "Schema must declare $id.");
        Assert.Contains("/1.0.0/schema.json", id.GetString());

        Assert.True(root.TryGetProperty("x-bcm-version", out var ver),
            "Schema must declare a top-level x-bcm-version annotation.");
        Assert.Equal("1.0.0", ver.GetString());
    }

    [Fact]
    public void Generated_Payloads_All_Validate_Against_Runtime_Schema()
    {
        var options = DefaultOptions();
        var validator = BuildValidator(options);
        var factory = BuildFactory(options);

        // Generate a long sequence — covers all simulated cases AND the full tier
        // progression (T0→T1, T1→T2, T2→T3, then wrap-around at T0).
        for (var i = 0; i < 200; i++)
        {
            var (payload, caseId) = factory.BuildNext(i);
            // Should not throw.
            validator.Validate(payload);
            Assert.False(string.IsNullOrWhiteSpace(payload),
                $"Payload for iteration {i} (case {caseId}) must not be empty.");
        }
    }

    [Fact]
    public void Every_Generated_Payload_Has_Sens_FRANCHISSEMENT()
    {
        var options = DefaultOptions();
        var factory = BuildFactory(options);

        for (var i = 0; i < 100; i++)
        {
            var (payload, _) = factory.BuildNext(i);
            using var doc = System.Text.Json.JsonDocument.Parse(payload);
            var sens = doc.RootElement.GetProperty("sens").GetString();
            Assert.Equal("FRANCHISSEMENT", sens);
        }
    }

    [Fact]
    public void Generated_Payloads_Have_Strictly_Upward_Tier_Transition()
    {
        // The stub must never simulate a downward crossing — Epic 1 scope.
        var options = DefaultOptions();
        var factory = BuildFactory(options);

        for (var i = 0; i < 100; i++)
        {
            var (payload, _) = factory.BuildNext(i);
            using var doc = System.Text.Json.JsonDocument.Parse(payload);
            var prev = doc.RootElement.GetProperty("palier_precedent").GetString()!;
            var next = doc.RootElement.GetProperty("nouveau_palier").GetString()!;
            var prevIdx = options.TierProgression.IndexOf(prev);
            var nextIdx = options.TierProgression.IndexOf(next);
            Assert.True(prevIdx >= 0, $"palier_precedent '{prev}' must be in the configured progression.");
            Assert.True(nextIdx >= 0, $"nouveau_palier '{next}' must be in the configured progression.");
            Assert.True(nextIdx > prevIdx,
                $"Upward only: nouveau_palier ({next}@{nextIdx}) must be strictly higher than palier_precedent ({prev}@{prevIdx}).");
        }
    }

    [Fact]
    public void Invalid_Payload_Is_Rejected_By_Validator()
    {
        // Sanity check: the validator must actually reject a malformed payload.
        var validator = BuildValidator(DefaultOptions());

        // sens is wrong (RETROGRADATION not allowed by Epic 1 schema).
        var badPayload = """
        {
          "identifiant_transition": "TRX-1",
          "identifiant_dossier": "DOS-X",
          "palier_precedent": "T1",
          "nouveau_palier": "T0",
          "sens": "RETROGRADATION",
          "declencheur": "ALGORITHME",
          "score_au_moment": 50.0,
          "timestamp_transition": "2026-04-28T10:00:00Z",
          "est_sortie_programme": false
        }
        """;

        Assert.Throws<SchemaValidationException>(() => validator.Validate(badPayload));
    }

    [Fact]
    public void Missing_Required_Field_Is_Rejected_By_Validator()
    {
        var validator = BuildValidator(DefaultOptions());

        // Missing identifiant_dossier (correlation key — must always be present).
        var badPayload = """
        {
          "identifiant_transition": "TRX-1",
          "palier_precedent": "T0",
          "nouveau_palier": "T1",
          "sens": "FRANCHISSEMENT",
          "declencheur": "ALGORITHME",
          "score_au_moment": 50.0,
          "timestamp_transition": "2026-04-28T10:00:00Z",
          "est_sortie_programme": false
        }
        """;

        Assert.Throws<SchemaValidationException>(() => validator.Validate(badPayload));
    }
}
