using System;
using System.IO;
using System.Linq;
using Xunit;

namespace Reliever.BehaviouralScore.Stub.Tests;

/// <summary>
/// CI unit tests — verify, independently of bus availability, that:
///   1. Every payload generated by <see cref="PayloadFactory"/> validates
///      against the runtime JSON Schema RVT.BSP.001.CURRENT_SCORE_RECOMPUTED.
///   2. The cadence guard enforces the [1, 10] events/min default range,
///      with an explicit override flag for outside-range values.
/// These checks satisfy the Definition of Done requirement that "every
/// payload validates against the runtime JSON Schema (automated check)".
/// </summary>
public class PayloadValidationTests
{
    private static SchemaValidator LoadValidator()
    {
        // Walk up from bin/Debug/net10.0/ until the repo root (containing
        // plan/CAP.BSP.001.SCO/contracts/) is found, then resolve the schema.
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            var candidate = Path.Combine(dir.FullName,
                "plan", "CAP.BSP.001.SCO", "contracts",
                "RVT.BSP.001.CURRENT_SCORE_RECOMPUTED.schema.json");
            if (File.Exists(candidate))
            {
                return SchemaValidator.FromFile(candidate);
            }
            dir = dir.Parent;
        }
        throw new FileNotFoundException(
            "Cannot locate plan/CAP.BSP.001.SCO/contracts/RVT.BSP.001.CURRENT_SCORE_RECOMPUTED.schema.json " +
            "by walking parents of " + AppContext.BaseDirectory);
    }

    private static StubOptions DefaultOptions() => new()
    {
        Active = true,
        CadencePerMinute = 5,
        ExchangeName = "bsp.001.sco-events",
        RoutingKey = "EVT.BSP.001.SCORE_RECOMPUTED.RVT.BSP.001.CURRENT_SCORE_RECOMPUTED",
        ModelVersion = "stub-1.0.0",
        SimulatedCases = new() { "CASE-RELIEVER-2026-000001", "CASE-RELIEVER-2026-000002" },
        EvaluationTypeMix = new() { ["INITIAL"] = 0.2, ["CURRENT"] = 0.8 },
    };

    [Fact]
    public void Generated_payloads_validate_against_runtime_schema()
    {
        var validator = LoadValidator();
        var factory = new PayloadFactory(DefaultOptions(), new Random(42));

        for (var i = 0; i < 200; i++)
        {
            var payload = factory.BuildOne();
            var errors = validator.Validate(payload);
            Assert.True(errors.Count == 0,
                $"Payload #{i} failed validation: {string.Join("; ", errors)}\nPayload: {payload}");
        }
    }

    [Fact]
    public void EnsureValid_throws_on_corrupted_payload()
    {
        var validator = LoadValidator();
        var factory = new PayloadFactory(DefaultOptions(), new Random(7));
        var payload = factory.BuildOne();

        // Remove a required field to force a schema violation.
        payload.Remove("case_id");

        Assert.Throws<InvalidPayloadException>(() => validator.EnsureValid(payload));
    }

    [Theory]
    [InlineData(1)]
    [InlineData(5)]
    [InlineData(10)]
    public void Cadence_within_default_range_is_accepted(int rate)
    {
        var opts = DefaultOptions();
        opts.CadencePerMinute = rate;
        opts.CadenceOutsideRangeOverride = false;

        var ex = Record.Exception(() => Worker.ValidateCadence(opts));
        Assert.Null(ex);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(11)]
    [InlineData(60)]
    public void Cadence_outside_default_range_requires_override(int rate)
    {
        var opts = DefaultOptions();
        opts.CadencePerMinute = rate;
        opts.CadenceOutsideRangeOverride = false;

        Assert.Throws<InvalidOperationException>(() => Worker.ValidateCadence(opts));
    }

    [Theory]
    [InlineData(11)]
    [InlineData(60)]
    public void Cadence_outside_default_range_with_override_is_accepted(int rate)
    {
        var opts = DefaultOptions();
        opts.CadencePerMinute = rate;
        opts.CadenceOutsideRangeOverride = true;

        var ex = Record.Exception(() => Worker.ValidateCadence(opts));
        Assert.Null(ex);
    }
}
