using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Reliever.EnvelopeManagement.Stub;
using Xunit;

namespace Reliever.EnvelopeManagement.Stub.Tests;

/// <summary>
/// CI unit tests verifying that the development stub honors the Definition of Done:
///
///  - every payload generated by PayloadFactory validates against the runtime
///    JSON Schema (RVT.BSP.004.CONSUMPTION_RECORDED);
///  - the schema's $id encodes the version segment and the x-bcm-version annotation
///    matches '1.0.0';
///  - every payload carries the correlation key (case_id) and the post-transition
///    coherence (consumed_amount_after, remaining_amount) demanded by the domain;
///  - the validator rejects malformed payloads (missing case_id, etc.).
///
/// These tests are the automated guardrail recommended by the DoD; they fail
/// loudly the moment the stub or the schema drifts from the BCM contract.
/// </summary>
public sealed class PayloadValidatesAgainstSchemaTests
{
    private const string SchemaRelativePath = "schemas/RVT.BSP.004.CONSUMPTION_RECORDED.schema.json";

    private static StubOptions DefaultOptions() => new()
    {
        Active = true,
        EventsPerMinute = 6,
        AllowOutOfRangeCadence = false,
        Cases = new()
        {
            new SimulatedCase
            {
                CaseId = "CASE-TEST-1",
                PeriodIndex = 0,
                PeriodStart = "2026-05-01",
                PeriodEnd = "2026-05-31",
                Envelopes = new()
                {
                    new SimulatedEnvelope { AllocationId = "ALLOC-T1-ALI", Category = "ALIMENTATION", CapAmount = 200.0 },
                    new SimulatedEnvelope { AllocationId = "ALLOC-T1-TRA", Category = "TRANSPORT",    CapAmount = 100.0 }
                }
            },
            new SimulatedCase
            {
                CaseId = "CASE-TEST-2",
                PeriodIndex = 0,
                PeriodStart = "2026-05-01",
                PeriodEnd = "2026-05-31",
                Envelopes = new()
                {
                    new SimulatedEnvelope { AllocationId = "ALLOC-T2-ALI", Category = "ALIMENTATION", CapAmount = 300.0 },
                    new SimulatedEnvelope { AllocationId = "ALLOC-T2-LOI", Category = "LOISIRS",      CapAmount =  50.0 },
                    new SimulatedEnvelope { AllocationId = "ALLOC-T2-VET", Category = "VETEMENTS",    CapAmount =  75.0 }
                }
            }
        },
        Schema = new SchemaOptions { RuntimeSchemaPath = SchemaRelativePath }
    };

    private static SchemaValidator BuildValidator(StubOptions options)
        => new(Options.Create(options), NullLogger<SchemaValidator>.Instance);

    private static PayloadFactory BuildFactory(StubOptions options)
        => new(Options.Create(options), NullLogger<PayloadFactory>.Instance);

    [Fact]
    public void Schema_File_Is_Present_Next_To_Tests()
    {
        var path = Path.Combine(AppContext.BaseDirectory, SchemaRelativePath);
        Assert.True(File.Exists(path),
            $"Runtime schema must be copied to test output at '{path}'.");
    }

    [Fact]
    public void Schema_Encodes_Version_In_Both_Id_And_X_Bcm_Version()
    {
        // Parse the raw JSON: NJsonSchema's loader normalises some root-level
        // properties — assert at the source-of-truth level (the JSON document).
        var path = Path.Combine(AppContext.BaseDirectory, SchemaRelativePath);
        var schemaJson = File.ReadAllText(path);
        using var doc = System.Text.Json.JsonDocument.Parse(schemaJson);
        var root = doc.RootElement;

        Assert.True(root.TryGetProperty("$id", out var id), "Schema must declare $id.");
        Assert.Contains("/1.0.0/schema.json", id.GetString());

        Assert.True(root.TryGetProperty("x-bcm-version", out var ver),
            "Schema must declare a top-level x-bcm-version annotation.");
        Assert.Equal("1.0.0", ver.GetString());
    }

    [Fact]
    public void Generated_Payloads_All_Validate_Against_Runtime_Schema()
    {
        var options = DefaultOptions();
        var validator = BuildValidator(options);
        var factory = BuildFactory(options);

        // Generate a long sequence — covers all simulated cases AND multiple
        // wrap-around cycles (envelope reaches cap, then resets to 0).
        for (var i = 0; i < 500; i++)
        {
            var (payload, caseId, allocId) = factory.BuildNext(i);
            validator.Validate(payload); // Should not throw.
            Assert.False(string.IsNullOrWhiteSpace(payload),
                $"Payload for iteration {i} (case {caseId}, alloc {allocId}) must not be empty.");
        }
    }

    [Fact]
    public void Every_Generated_Payload_Carries_Case_Id_Correlation_Key()
    {
        var options = DefaultOptions();
        var factory = BuildFactory(options);

        for (var i = 0; i < 100; i++)
        {
            var (payload, caseId, _) = factory.BuildNext(i);
            using var doc = System.Text.Json.JsonDocument.Parse(payload);
            Assert.True(doc.RootElement.TryGetProperty("case_id", out var case_id),
                "case_id is the correlation key — every payload MUST carry it.");
            Assert.Equal(caseId, case_id.GetString());
        }
    }

    [Fact]
    public void Generated_Payloads_Have_Coherent_Remaining_Amount()
    {
        // Domain rule (per RVT.BSP.004.CONSUMPTION_RECORDED schema):
        // remaining_amount = cap_amount - consumed_amount_after.
        // The stub holds cap_amount in StubOptions.Cases[].Envelopes[]; verify the
        // arithmetic transmitted on the wire matches.
        var options = DefaultOptions();
        var factory = BuildFactory(options);

        var caps = options.Cases
            .SelectMany(c => c.Envelopes)
            .ToDictionary(e => e.AllocationId, e => e.CapAmount);

        for (var i = 0; i < 200; i++)
        {
            var (payload, _, allocId) = factory.BuildNext(i);
            using var doc = System.Text.Json.JsonDocument.Parse(payload);
            var consumedAfter = doc.RootElement.GetProperty("consumed_amount_after").GetDouble();
            var remaining = doc.RootElement.GetProperty("remaining_amount").GetDouble();
            var cap = caps[allocId];

            Assert.True(consumedAfter >= 0, $"consumed_amount_after must be >= 0 (got {consumedAfter}).");
            Assert.True(remaining >= 0, $"remaining_amount must be >= 0 (got {remaining}).");
            Assert.True(consumedAfter <= cap + 0.001,
                $"consumed_amount_after ({consumedAfter}) must not exceed cap ({cap}).");
            Assert.InRange(consumedAfter + remaining, cap - 0.01, cap + 0.01);
        }
    }

    [Fact]
    public void Generated_Payloads_Have_Positive_Amount()
    {
        // Domain rule INV.ENV.003: amount > 0 (strict).
        var options = DefaultOptions();
        var factory = BuildFactory(options);

        for (var i = 0; i < 100; i++)
        {
            var (payload, _, _) = factory.BuildNext(i);
            using var doc = System.Text.Json.JsonDocument.Parse(payload);
            var amount = doc.RootElement.GetProperty("amount").GetDouble();
            Assert.True(amount > 0, $"amount must be strictly > 0 (got {amount}).");
        }
    }

    [Fact]
    public void Generated_Payloads_Cycle_Across_Configured_Cases()
    {
        // The stub must round-robin across ALL configured cases (DoD: configurable
        // simulated case_ids — at least one default, ideally several).
        var options = DefaultOptions();
        var factory = BuildFactory(options);

        var seenCases = new HashSet<string>();
        for (var i = 0; i < 50; i++)
        {
            var (_, caseId, _) = factory.BuildNext(i);
            seenCases.Add(caseId);
        }

        Assert.Equal(options.Cases.Select(c => c.CaseId).ToHashSet(), seenCases);
    }

    [Fact]
    public void Invalid_Payload_Missing_Correlation_Key_Is_Rejected()
    {
        // The validator must actually reject a payload that omits case_id.
        var validator = BuildValidator(DefaultOptions());

        var badPayload = """
        {
          "event_id": "EVT-1",
          "occurred_at": "2026-05-09T10:00:00Z",
          "period_index": 0,
          "allocation_id": "ALLOC-X",
          "category": "ALIMENTATION",
          "amount": 12.50,
          "consumed_amount_after": 12.50,
          "remaining_amount": 87.50
        }
        """;

        Assert.Throws<SchemaValidationException>(() => validator.Validate(badPayload));
    }

    [Fact]
    public void Invalid_Payload_With_Negative_Amount_Is_Rejected()
    {
        // Domain rule: amount > 0 (exclusiveMinimum: 0). Negative or zero amount
        // must fail validation.
        var validator = BuildValidator(DefaultOptions());

        var badPayload = """
        {
          "event_id": "EVT-1",
          "occurred_at": "2026-05-09T10:00:00Z",
          "case_id": "CASE-X",
          "period_index": 0,
          "allocation_id": "ALLOC-X",
          "category": "ALIMENTATION",
          "amount": -5.0,
          "consumed_amount_after": 12.50,
          "remaining_amount": 87.50
        }
        """;

        Assert.Throws<SchemaValidationException>(() => validator.Validate(badPayload));
    }

    [Fact]
    public void Invalid_Payload_With_Additional_Property_Is_Rejected()
    {
        // additionalProperties: false — no unexpected fields on the wire.
        var validator = BuildValidator(DefaultOptions());

        var badPayload = """
        {
          "event_id": "EVT-1",
          "occurred_at": "2026-05-09T10:00:00Z",
          "case_id": "CASE-X",
          "period_index": 0,
          "allocation_id": "ALLOC-X",
          "category": "ALIMENTATION",
          "amount": 5.0,
          "consumed_amount_after": 12.50,
          "remaining_amount": 87.50,
          "internal_id": "BEN-001"
        }
        """;

        Assert.Throws<SchemaValidationException>(() => validator.Validate(badPayload));
    }
}
