using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Reliever.BudgetEnvelopeManagement.Stub;
using Xunit;

namespace Reliever.BudgetEnvelopeManagement.Stub.Tests;

/// <summary>
/// CI unit tests verifying that the development stub honors the Definition of Done:
///
///  - every payload generated by PayloadFactory validates against the runtime
///    JSON Schema (RVT.BSP.004.CONSUMPTION_RECORDED);
///  - the runtime invariant (montant_consomme <= montant_plafond) holds for every payload;
///  - the schema's $id encodes the version segment and the x-bcm-version annotation
///    matches.
///
/// These tests are the automated guardrail recommended by the DoD; they fail
/// loudly the moment the stub or the schema drifts from the BCM contract.
/// </summary>
public sealed class PayloadValidatesAgainstSchemaTests
{
    private const string SchemaRelativePath = "schemas/RVT.BSP.004.CONSUMPTION_RECORDED.schema.json";

    private static StubOptions DefaultOptions() => new()
    {
        Active = true,
        EventsPerMinute = 6,
        AllowOutOfRangeCadence = false,
        DefaultMontantPlafond = 200.00,
        TransitionsPerEnvelope = 6,
        Cases = new()
        {
            new SimulatedCase { CaseId = "DOS-TEST-1", Categories = new() { "ALIMENTATION", "TRANSPORT" } },
            new SimulatedCase { CaseId = "DOS-TEST-2", Categories = new() { "SANTE", "LOGEMENT", "ENERGIE" } }
        },
        Schema = new SchemaOptions { RuntimeSchemaPath = SchemaRelativePath }
    };

    private static SchemaValidator BuildValidator(StubOptions options)
        => new(Options.Create(options), NullLogger<SchemaValidator>.Instance);

    private static PayloadFactory BuildFactory(StubOptions options)
        => new(Options.Create(options), NullLogger<PayloadFactory>.Instance);

    [Fact]
    public void Schema_File_Is_Present_Next_To_Tests()
    {
        var path = Path.Combine(AppContext.BaseDirectory, SchemaRelativePath);
        Assert.True(File.Exists(path),
            $"Runtime schema must be copied to test output at '{path}'.");
    }

    [Fact]
    public void Schema_Encodes_Version_In_Both_Id_And_X_Bcm_Version()
    {
        // Parse the raw JSON: NJsonSchema's loader normalises some root-level
        // properties — assert at the source-of-truth level (the JSON document).
        var path = Path.Combine(AppContext.BaseDirectory, SchemaRelativePath);
        var schemaJson = File.ReadAllText(path);
        using var doc = System.Text.Json.JsonDocument.Parse(schemaJson);
        var root = doc.RootElement;

        Assert.True(root.TryGetProperty("$id", out var id), "Schema must declare $id.");
        Assert.Contains("/1.0.0/schema.json", id.GetString());

        Assert.True(root.TryGetProperty("x-bcm-version", out var ver),
            "Schema must declare a top-level x-bcm-version annotation.");
        Assert.Equal("1.0.0", ver.GetString());
    }

    [Fact]
    public void Schema_Declares_Correlation_Key_Identifiant_Dossier()
    {
        var path = Path.Combine(AppContext.BaseDirectory, SchemaRelativePath);
        var schemaJson = File.ReadAllText(path);
        using var doc = System.Text.Json.JsonDocument.Parse(schemaJson);
        var root = doc.RootElement;

        Assert.True(root.TryGetProperty("x-bcm-correlation-key", out var corrKey),
            "Schema must declare the correlation key as a top-level annotation.");
        Assert.Equal("identifiant_dossier", corrKey.GetString());

        Assert.True(root.TryGetProperty("required", out var required));
        var requiredFields = new HashSet<string>();
        foreach (var elem in required.EnumerateArray())
        {
            requiredFields.Add(elem.GetString()!);
        }
        Assert.Contains("identifiant_dossier", requiredFields);
    }

    [Fact]
    public void Schema_Annotates_Payload_Form_Domain_Event_DDD()
    {
        var path = Path.Combine(AppContext.BaseDirectory, SchemaRelativePath);
        var schemaJson = File.ReadAllText(path);
        using var doc = System.Text.Json.JsonDocument.Parse(schemaJson);
        var root = doc.RootElement;

        Assert.True(root.TryGetProperty("x-bcm-payload-form", out var form),
            "Schema must declare its payload form as a top-level annotation.");
        Assert.Equal("domain-event-DDD", form.GetString());
    }

    [Fact]
    public void Schema_Description_Documents_Solde_Disponible_Formula()
    {
        // The available balance (solde_disponible = montant_plafond - montant_consomme)
        // MUST be documented in the runtime schema description per DoD — but it MUST NOT
        // be a transported field.
        var path = Path.Combine(AppContext.BaseDirectory, SchemaRelativePath);
        var schemaJson = File.ReadAllText(path);
        using var doc = System.Text.Json.JsonDocument.Parse(schemaJson);
        var root = doc.RootElement;

        var description = root.GetProperty("description").GetString()!;
        Assert.Contains("solde_disponible", description);
        Assert.Contains("montant_plafond - montant_consomme", description);

        // And solde_disponible is NOT in the properties.
        var properties = root.GetProperty("properties");
        Assert.False(properties.TryGetProperty("solde_disponible", out _),
            "solde_disponible MUST NOT be a transported field — it is derived consumer-side.");
    }

    [Fact]
    public void Generated_Payloads_All_Validate_Against_Runtime_Schema()
    {
        var options = DefaultOptions();
        var validator = BuildValidator(options);
        var factory = BuildFactory(options);

        // Generate a long sequence — covers all (case × category) allocations and
        // multiple envelope reset cycles.
        for (var i = 0; i < 500; i++)
        {
            var (payload, caseId, category) = factory.BuildNext(i);
            // Should not throw.
            validator.Validate(payload);
            Assert.False(string.IsNullOrWhiteSpace(payload),
                $"Payload for iteration {i} (case {caseId}, category {category}) must not be empty.");
        }
    }

    [Fact]
    public void Every_Generated_Payload_Honors_Cap_Invariant()
    {
        // Domain rule: 0 <= montant_consomme <= montant_plafond.
        var options = DefaultOptions();
        var factory = BuildFactory(options);

        for (var i = 0; i < 500; i++)
        {
            var (payload, _, _) = factory.BuildNext(i);
            using var doc = System.Text.Json.JsonDocument.Parse(payload);
            var plafond = doc.RootElement.GetProperty("montant_plafond").GetDouble();
            var consomme = doc.RootElement.GetProperty("montant_consomme").GetDouble();
            Assert.True(consomme >= 0,
                $"Iteration {i}: montant_consomme={consomme} must be >= 0.");
            Assert.True(consomme <= plafond,
                $"Iteration {i}: montant_consomme={consomme} must be <= montant_plafond={plafond}.");
            Assert.True(plafond > 0,
                $"Iteration {i}: montant_plafond={plafond} must be > 0.");
        }
    }

    [Fact]
    public void Generated_Payloads_Cover_All_Configured_Categories()
    {
        // Round-robin must visit every (case, category) allocation at least once
        // within a full cycle.
        var options = DefaultOptions();
        var factory = BuildFactory(options);

        var seen = new HashSet<(string CaseId, string Category)>();
        var totalAllocations = options.Cases.Sum(c => c.Categories.Count);

        for (var i = 0; i < totalAllocations * 3; i++)
        {
            var (_, caseId, category) = factory.BuildNext(i);
            seen.Add((caseId, category));
        }

        Assert.Equal(totalAllocations, seen.Count);
    }

    [Fact]
    public void Generated_Payloads_Carry_Identifiant_Dossier_Correlation_Key()
    {
        var options = DefaultOptions();
        var factory = BuildFactory(options);

        for (var i = 0; i < 50; i++)
        {
            var (payload, caseId, _) = factory.BuildNext(i);
            using var doc = System.Text.Json.JsonDocument.Parse(payload);
            Assert.True(doc.RootElement.TryGetProperty("identifiant_dossier", out var idDossier));
            Assert.Equal(caseId, idDossier.GetString());
        }
    }

    [Fact]
    public void Generated_Payloads_Do_Not_Carry_Solde_Disponible()
    {
        // Available balance is derivable consumer-side and MUST NOT be carried on the wire.
        var options = DefaultOptions();
        var factory = BuildFactory(options);

        for (var i = 0; i < 100; i++)
        {
            var (payload, _, _) = factory.BuildNext(i);
            using var doc = System.Text.Json.JsonDocument.Parse(payload);
            Assert.False(doc.RootElement.TryGetProperty("solde_disponible", out _),
                "solde_disponible MUST NOT be a transported field — derivation is consumer-side.");
        }
    }

    [Fact]
    public void Generated_Payloads_Do_Not_Carry_Identifiant_Interne()
    {
        // Privacy + decoupling per ADR-BCM-URBA-0009 — the canonical beneficiary identifier
        // is never carried on the bus; consumers resolve via CAP.REF.001.BEN.
        var options = DefaultOptions();
        var factory = BuildFactory(options);

        for (var i = 0; i < 50; i++)
        {
            var (payload, _, _) = factory.BuildNext(i);
            using var doc = System.Text.Json.JsonDocument.Parse(payload);
            Assert.False(doc.RootElement.TryGetProperty("identifiant_interne", out _),
                "identifiant_interne MUST NOT be carried on the bus.");
        }
    }

    [Fact]
    public void Invalid_Payload_Is_Rejected_By_Validator()
    {
        // Sanity check: the validator must actually reject a malformed payload.
        var validator = BuildValidator(DefaultOptions());

        // montant_plafond <= 0 is forbidden (exclusiveMinimum=0).
        var badPayload = """
        {
          "identifiant_allocation": "ALC-1",
          "identifiant_dossier": "DOS-X",
          "categorie": "ALIMENTATION",
          "montant_plafond": 0,
          "montant_consomme": 0,
          "periode_debut": "2026-05-01",
          "periode_fin": "2026-05-31",
          "timestamp_consommation": "2026-05-05T10:00:00Z"
        }
        """;

        Assert.Throws<SchemaValidationException>(() => validator.Validate(badPayload));
    }

    [Fact]
    public void Missing_Correlation_Key_Is_Rejected_By_Validator()
    {
        var validator = BuildValidator(DefaultOptions());

        // Missing identifiant_dossier (correlation key — must always be present).
        var badPayload = """
        {
          "identifiant_allocation": "ALC-1",
          "categorie": "ALIMENTATION",
          "montant_plafond": 200.0,
          "montant_consomme": 50.0,
          "periode_debut": "2026-05-01",
          "periode_fin": "2026-05-31",
          "timestamp_consommation": "2026-05-05T10:00:00Z"
        }
        """;

        Assert.Throws<SchemaValidationException>(() => validator.Validate(badPayload));
    }

    [Fact]
    public void Additional_Properties_Are_Rejected_By_Validator()
    {
        // additionalProperties: false — wire surface is closed.
        var validator = BuildValidator(DefaultOptions());

        var badPayload = """
        {
          "identifiant_allocation": "ALC-1",
          "identifiant_dossier": "DOS-X",
          "categorie": "ALIMENTATION",
          "montant_plafond": 200.0,
          "montant_consomme": 50.0,
          "periode_debut": "2026-05-01",
          "periode_fin": "2026-05-31",
          "timestamp_consommation": "2026-05-05T10:00:00Z",
          "solde_disponible": 150.0
        }
        """;

        Assert.Throws<SchemaValidationException>(() => validator.Validate(badPayload));
    }
}
